apiVersion: v1
kind: Pod
metadata:
  name: zhanyi-inventory
  labels:
    app: zhanyi-inventory
    app-pod: zhanyi-inventory-pod
spec:
  containers:
  - name: inventory-service
    image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/zhanyi/inventory-service:latest
    ports:
    - containerPort: 8080
---    
apiVersion: v1
kind: Service
metadata:
  name: zhanyi-inventory-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31400
  selector:
    app-pod: zhanyi-inventory-pod