apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-02-08T04:00:58Z
  name: zhanyi-inventory-service
  namespace: zhanyi-space
  resourceVersion: "344366"
  selfLink: /api/v1/namespaces/zhanyi-space/services/zhanyi-inventory-service
  uid: ab719a7b-0c84-11e8-8869-061db4bae23c
spec:
  clusterIP: 10.101.149.80
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31400
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: inventory-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
